import "@/styles/globals.css";

import type { Metadata } from "next";
import { cookies } from "next/headers";

import { cn } from "@/lib/utils";
import { fontSans } from "@/utils/fonts";
import { TRPCReactProvider } from "@/trpc/react";

export const metadata: Metadata = {
	title: "Create Z0 App",
	description: "Generated by create-z0-app",
	icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<body className={cn("font-sans", fontSans.variable)}>
				<TRPCReactProvider cookies={cookies().toString()}>
          {children}
        </TRPCReactProvider></body>
		</html>
	);
}
